### PR TITLE
[ENHANCEMENT] adding hook to allow user defaults for AJAX requests

### PR DESCRIPTION
**Pull request by williamsbdev**
Also do not set the contentType to "application/json" when it is a GET
request as a body is not material to a GET request and therefore should
not need to specify a contentType.

### CODE REVIEW

**Comment by williamsbdev** [comment]
This is not ready to merge. I will have some more changes to make this work.

**Comment by williamsbdev** [comment]
@toranb I merged this but would love your feedback when you get some time to look this over. I'm planning on a beta release to make sure this is what we would like.

**Comment by toranb** [comment]
Looks good - my only question is ... what version of this / fauxjax / ember-cli-test-helpers work (best) together now / going forward?

**Comment by williamsbdev** [comment]
To have best results, it is recommended to use these versions:

ember-promise: 1.2.0
ember-cli-test-helpers: 1.6.0
fauxjax: 1.2.1

**Pull request merged**
